[project]
name = "dagster-dingtalk"
version = "0.1.35"
description = "A dagster plugin for the DingTalk"
readme = "README.md"
authors = [
    { name = "YiZixuan", email = "sqkkyzx@qq.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "pydantic",
    "dagster>1.10.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
